<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Compare run for the &quot;General Content Detail Page&quot; page type only. Capture the new side, then diff it against the live snapshot and rebuild the reports. Needs VPN.</description>
   <name>TS_GeneralContentDetailPage_Compare</name>
   <tag>normal,general-content-detail-page,compare,by-page</tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <maxConcurrentInstances>1</maxConcurrentInstances>
   <numberOfRerun>0</numberOfRerun>
   <orchestration>CLASSIC</orchestration>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>08f5c9da-d1e8-4990-b1c9-f680dbf99de9</testSuiteGuid>
   <testCaseLink>
      <guid>e255e7b5-3226-436c-8850-83812aab674f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/migration-aem/templates/normal-pages/TC_GeneralContentDetailPage</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1f791968-4f32-4dd0-a1ce-4dd2bf94e8d4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/url-mapping/normal-pages/GeneralContentDetailPage</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1f791968-4f32-4dd0-a1ce-4dd2bf94e8d4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>aemurl</value>
         <variableId>c647c4ac-b521-47d1-9d24-822d03bb3b0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1f791968-4f32-4dd0-a1ce-4dd2bf94e8d4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>aemtemplate</value>
         <variableId>7d00176a-304d-471b-ae25-3ec4f7a91ff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1f791968-4f32-4dd0-a1ce-4dd2bf94e8d4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>sitecoreurl</value>
         <variableId>d5e3c615-52cf-45f8-8ff2-4205789ae6aa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1f791968-4f32-4dd0-a1ce-4dd2bf94e8d4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pagetype</value>
         <variableId>14d0f79d-1d5b-4f02-93c3-62914876d149</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>'compare'</value>
         <variableId>4761f407-5b7b-4baf-aafa-087b457f55ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>'https://www.prudential.com.sg'</value>
         <variableId>6251c295-ce11-4542-a0d5-b560c86d2c23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>'https://aem-uat.prudential.com.sg'</value>
         <variableId>48802c88-70bb-4bf0-8f55-6e39aed69ce7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c97caae-c782-4aee-9774-44f0b7b28f3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/migration-aem/checks/TC_Build_Parity_Report</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
